services:
  - type: web
    name: research-assistant
    env: node
    region: oregon
    plan: free
    buildCommand: "curl -L -o java.tar.gz https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.11+9/OpenJDK17U-jdk_x64_linux_hotspot_17.0.11_9.tar.gz && tar -xzf java.tar.gz && rm java.tar.gz && npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_HOME
        value: "./jdk-17.0.11+9"
      - key: PATH
        sync: false
        value: "$JAVA_HOME/bin:$PATH"