services:
  - type: web
    name: research-assistant
    env: node
    region: oregon
    plan: free
    buildCommand: "bash -c 'apt-get update && apt-get install -y openjdk-17-jdk && npm install'"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8080